# Generated by Django 5.1.3 on 2024-11-13 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('Nombre', models.CharField(max_length=30, null=True)),
                ('Apellido', models.CharField(max_length=30, null=True)),
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('Celular', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('Nombre', models.CharField(max_length=30, null=True)),
                ('Apellido', models.CharField(max_length=30, null=True)),
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Fecha_de_naciemiento', models.DateField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('Celular', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Calif.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('Calificacion', models.FloatField()),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Calif.estudiante')),
                ('Materia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Calif.materia')),
            ],
        ),
    ]
